"use strict";

const { stableStringify } = require("../dist-io");

// Node type → id prefix. The id is `<prefix>:<slug>`; prefixes dissolve
// cross-domain slug collisions (e.g. a11y:color-contrast vs foundation:color-contrast).
var PREFIX = {
  component: "component",
  category: "category",
  a11y_criterion: "a11y",
  foundation_section: "foundation",
  motion_pattern: "motion",
  content_topic: "content",
};

function nodeId(type, slug) {
  if (!PREFIX[type]) throw new Error("graph: unknown node type '" + type + "'");
  if (!slug)
    throw new Error(
      "graph: nodeId requires a non-empty slug (type '" +
        type +
        "', got: " +
        JSON.stringify(slug) +
        ")",
    );
  return PREFIX[type] + ":" + slug;
}

// Deterministic slug: lowercase, non-alphanumeric runs → "-", trim "-".
function slugify(label) {
  return String(label)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function GraphBuilder() {
  this._nodes = new Map(); // id → node (first wins)
  this._edges = new Map(); // "type|source|target" → edge (first wins)
}
GraphBuilder.prototype.addNode = function (node) {
  if (!node || !node.id) throw new Error("graph: node missing id");
  if (!this._nodes.has(node.id)) this._nodes.set(node.id, node);
  return this;
};
GraphBuilder.prototype.addEdge = function (edge) {
  var key = edge.type + "|" + edge.source + "|" + edge.target;
  if (!this._edges.has(key)) this._edges.set(key, edge);
  return this;
};
GraphBuilder.prototype.hasNode = function (id) {
  return this._nodes.has(id);
};
GraphBuilder.prototype.build = function () {
  var nodes = Array.from(this._nodes.values()).sort(function (a, b) {
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
  var edges = Array.from(this._edges.values()).sort(function (a, b) {
    // Ordinal (not localeCompare) for cross-locale determinism, matching the node sort.
    // Sort key is unambiguous: type is a fixed enum (no spaces); ids are namespace:slug
    // (slugify output never contains spaces).
    var ka = a.type + " " + a.source + " " + a.target;
    var kb = b.type + " " + b.source + " " + b.target;
    return ka < kb ? -1 : ka > kb ? 1 : 0;
  });
  return {
    _schema_version: 2,
    _meta: {
      auto_generated: true,
      generator: "scripts/graph/derive-graph.js",
      do_not_edit:
        "Regenerated by CI from the dist; edit the source substrate, not this file.",
    },
    nodes: nodes,
    edges: edges,
  };
};

module.exports = {
  PREFIX: PREFIX,
  nodeId: nodeId,
  slugify: slugify,
  stableStringify: stableStringify,
  GraphBuilder: GraphBuilder,
};
