"use strict";

// Node type → id prefix. The id is `<prefix>:<slug>`; prefixes dissolve
// cross-domain slug collisions (e.g. a11y:color-contrast vs foundation:color-contrast).
var PREFIX = {
  component: "component",
  category: "category",
  a11y_criterion: "a11y",
  foundation_section: "foundation",
  motion_pattern: "motion",
  content_topic: "content",
};

function nodeId(type, slug) {
  if (!PREFIX[type]) throw new Error("graph: unknown node type '" + type + "'");
  return PREFIX[type] + ":" + slug;
}

// Deterministic slug: lowercase, non-alphanumeric runs → "-", trim "-".
function slugify(label) {
  return String(label).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function stableStringify(obj) {
  return JSON.stringify(obj, null, 2) + "\n";
}

function GraphBuilder() {
  this._nodes = new Map(); // id → node (first wins)
  this._edges = [];
}
GraphBuilder.prototype.addNode = function (node) {
  if (!node || !node.id) throw new Error("graph: node missing id");
  if (!this._nodes.has(node.id)) this._nodes.set(node.id, node);
  return this;
};
GraphBuilder.prototype.addEdge = function (edge) {
  this._edges.push(edge);
  return this;
};
GraphBuilder.prototype.build = function () {
  var nodes = Array.from(this._nodes.values()).sort(function (a, b) {
    return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
  });
  var edges = this._edges.slice().sort(function (a, b) {
    return (a.type + " " + a.source + " " + a.target)
      .localeCompare(b.type + " " + b.source + " " + b.target);
  });
  return {
    _schema_version: 1,
    _meta: {
      auto_generated: true,
      generator: "scripts/graph/derive-graph.js",
      do_not_edit: "Regenerated by CI from the dist; edit the source substrate, not this file.",
    },
    nodes: nodes,
    edges: edges,
  };
};

module.exports = { PREFIX: PREFIX, nodeId: nodeId, slugify: slugify, stableStringify: stableStringify, GraphBuilder: GraphBuilder };
