"use strict";

// Builds a consolidated content.md from per-component source files.
// Section order comes from the index file's "All sections" anchors
// (<a href="slug">Title</a>). To reorder sections, edit the index —
// the generator follows.
//
// Run:
//   npm run derive:content
//   node scripts/content/derive-content.js \
//     --src content/src \
//     --index content/src/content-index.md \
//     --out content/dist/content.md

var fs = require("fs");
var path = require("path");

var ROOT = path.resolve(__dirname, "..", "..");

var KNOWN_FLAGS = ["src", "index", "out"];

function parseArgs(argv) {
  var out = {};
  for (var i = 0; i < argv.length; i++) {
    var token = argv[i];
    if (token.indexOf("--") !== 0) continue;
    var key = token.replace(/^--/, "");
    if (KNOWN_FLAGS.indexOf(key) === -1) {
      throw new Error(
        "unknown flag --" + key + " (known: " + KNOWN_FLAGS.join(", ") + ")",
      );
    }
    var value = argv[i + 1];
    if (value === undefined || value.indexOf("--") === 0) {
      throw new Error("flag --" + key + " requires a value");
    }
    out[key] = value;
    i++;
  }
  return out;
}

function resolveConfig(args) {
  var src = args.src
    ? path.resolve(ROOT, args.src)
    : path.join(ROOT, "content/src");
  var indexArg = args.index
    ? path.resolve(ROOT, args.index)
    : path.join(src, "content-index.md");
  var out = args.out
    ? path.resolve(ROOT, args.out)
    : path.join(ROOT, "content/dist/content.md");
  return { src: src, index: indexArg, out: out };
}

function readSectionOrder(indexFile) {
  if (!fs.existsSync(indexFile)) {
    throw new Error("index file not found: " + path.relative(ROOT, indexFile));
  }
  var md = fs.readFileSync(indexFile, "utf8");
  // Local regex — avoid module-scoped /g state across calls.
  var hrefRe = /<a href="([^"]+)">([^<]+)<\/a>/g;
  var order = [];
  var seen = new Set();
  var m;
  while ((m = hrefRe.exec(md))) {
    var slug = m[1].trim();
    var title = m[2].trim();
    if (seen.has(slug)) continue;
    seen.add(slug);
    order.push({ slug: slug, title: title });
  }
  if (order.length === 0) {
    throw new Error(
      path.relative(ROOT, indexFile) +
        ': no <a href="slug">Title</a> entries found',
    );
  }
  return order;
}

function stripFrontmatter(s) {
  return s.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "");
}

function stripJekyllAttrs(s) {
  // Strip the attribute line AND its trailing newline so we don't leave
  // an orphan blank line where it used to be.
  return s.replace(/^\s*\{:\s*[^}]+\}\s*\r?\n?/gm, "");
}

function collapseBlankLines(s) {
  // Normalize runs of 3+ newlines to exactly 2 (one blank line).
  return s.replace(/\n{3,}/g, "\n\n");
}

function shiftHeadings(s) {
  var lines = s.split("\n");
  var inCode = false;
  for (var i = 0; i < lines.length; i++) {
    if (/^```/.test(lines[i])) {
      inCode = !inCode;
      continue;
    }
    if (inCode) continue;
    var match = lines[i].match(/^(#{1,6}) (.*)$/);
    if (!match) continue;
    var hashes = match[1];
    if (hashes.length >= 6) continue;
    lines[i] = "#" + hashes + " " + match[2];
  }
  return lines.join("\n");
}

function readSection(srcDir, slug) {
  var file = path.join(srcDir, slug + ".md");
  if (!fs.existsSync(file)) return null;
  var s = fs.readFileSync(file, "utf8");
  s = s.replace(/\r\n/g, "\n");
  s = stripFrontmatter(s);
  s = stripJekyllAttrs(s);
  s = collapseBlankLines(s);
  s = s.trim();
  s = shiftHeadings(s);
  return s;
}

function buildOutput(config) {
  var order = readSectionOrder(config.index);
  var lines = [];
  lines.push("# Content guidelines — Actian Data Intelligence");
  lines.push("");
  lines.push(
    "> **Auto-generated** by `scripts/content/derive-content.js` from " +
      "`" +
      path.relative(ROOT, config.src) +
      "/*.md`. Do not edit this file directly — edit the per-component " +
      "source files.",
  );
  lines.push(">");
  lines.push(
    "> **Per-component sources:** `" +
      path.relative(ROOT, config.src) +
      "/{slug}.md` (" +
      order.length +
      " sections)",
  );
  lines.push(
    "> **Section order:** `" +
      path.relative(ROOT, config.index) +
      '` ("All sections" anchors)',
  );
  lines.push(
    "> **Authoring guide:** `" +
      path.relative(ROOT, config.src) +
      "/AUTHORING.md`",
  );
  lines.push("");
  lines.push("---");
  lines.push("");

  var missing = [];
  for (var i = 0; i < order.length; i++) {
    var body = readSection(config.src, order[i].slug);
    if (!body) {
      missing.push(order[i].slug);
      continue;
    }
    lines.push(body);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  if (missing.length > 0) {
    throw new Error(
      "Missing source files for " +
        missing.length +
        " section(s) referenced in " +
        path.relative(ROOT, config.index) +
        ": " +
        missing.join(", "),
    );
  }

  while (
    lines.length &&
    (lines[lines.length - 1] === "" || lines[lines.length - 1] === "---")
  ) {
    lines.pop();
  }
  lines.push("");

  return lines.join("\n");
}

function main(argv) {
  var args = parseArgs(argv);
  var config = resolveConfig(args);
  var output = buildOutput(config);
  var outDir = path.dirname(config.out);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(config.out, output);
  var stats = fs.statSync(config.out);
  console.log(
    "[derive-content] wrote " +
      path.relative(ROOT, config.out) +
      " (" +
      stats.size +
      " bytes, " +
      output.split("\n").length +
      " lines)",
  );
}

if (require.main === module) {
  try {
    main(process.argv.slice(2));
  } catch (err) {
    console.error("[derive-content] FAILED: " + err.message);
    process.exit(1);
  }
}

module.exports = {
  KNOWN_FLAGS: KNOWN_FLAGS,
  parseArgs: parseArgs,
  resolveConfig: resolveConfig,
  readSectionOrder: readSectionOrder,
  stripFrontmatter: stripFrontmatter,
  stripJekyllAttrs: stripJekyllAttrs,
  collapseBlankLines: collapseBlankLines,
  shiftHeadings: shiftHeadings,
  readSection: readSection,
  buildOutput: buildOutput,
};
