// Path tier classification — drives the TierBanner visual warning
// that appears above each editor surface. Three buckets:
//
//   read-only-figma-synced   — tokens/* + dist/registries/*; the Figma
//                              sync workflow rewrites these on every run
//   read-only-derived        — */dist/*, llms*.txt; regenerated by CI
//   read-only-lockstep       — paths-manifest.json; bump-version.js owns this
//   high-impact-foundations  — foundations/src/*.md; one file → many consumers
//   high-impact-accessibility — accessibility/src/*.md; same reach
//   high-impact-category     — components/src/categories/*.md; affects every
//                              component whose _meta.yml inherits the category
//   writable                 — default — no banner, normal authoring
//
// The classifier mirrors editor/src/core/validatePaths.ts's read-only
// rules and adds the "high-impact" tiers to catch cross-cutting edits
// before they ship as a "small change".

export type PathTier =
  | "writable"
  | "read-only-figma-synced"
  | "read-only-derived"
  | "read-only-lockstep"
  | "high-impact-foundations"
  | "high-impact-accessibility"
  | "high-impact-category";

export interface TierInfo {
  tier: PathTier;
  label: string;
  /** Authoring guidance — full sentence(s). */
  message: string;
  /** Severity color for the banner ("red" = read-only, "amber" = high-impact). */
  severity: "red" | "amber" | "none";
}

const READONLY_EXACT = new Set<string>([
  "tokens/tokens.json",
  "tokens/tokens.css",
  "tokens/token-reference.md",
  "llms.txt",
  "llms-full.txt",
  "paths-manifest.json",
]);

export function getPathTier(path: string): TierInfo {
  // ── Read-only ──────────────────────────────────────────────────────
  if (path === "paths-manifest.json") {
    return {
      tier: "read-only-lockstep",
      label: "Lockstep · read-only",
      message:
        "paths-manifest.json carries the knowledge_version lockstep. " +
        "bump-version.js owns updates here. Editing manually corrupts the " +
        "vendor snapshot workflow.",
      severity: "red",
    };
  }
  if (
    path.startsWith("tokens/") ||
    path.startsWith("components/dist/registries/")
  ) {
    return {
      tier: "read-only-figma-synced",
      label: "Figma-synced · read-only",
      message:
        "This file is regenerated by the sync-from-figma workflow on every " +
        "run. Manual edits will be silently overwritten on the next sync.",
      severity: "red",
    };
  }
  if (READONLY_EXACT.has(path) || /^[^/]+\/dist\//.test(path)) {
    return {
      tier: "read-only-derived",
      label: "CI-derived · read-only",
      message:
        "This file is regenerated by CI from source. Manual edits will be " +
        "silently overwritten.",
      severity: "red",
    };
  }

  // ── High-impact writable ───────────────────────────────────────────
  if (/^components\/src\/categories\/[^/]+\.md$/.test(path)) {
    return {
      tier: "high-impact-category",
      label: "Category default · cross-cutting",
      message:
        "This file is the default content for every component whose _meta.yml " +
        "declares the corresponding domain as inherited. A change here ripples " +
        "across every inheritor — review carefully.",
      severity: "amber",
    };
  }
  if (/^foundations\/src\/[^/]+\.md$/.test(path)) {
    return {
      tier: "high-impact-foundations",
      label: "Foundations · all consumers",
      message:
        "Foundations content is consumed by the plugin, the docs site, and " +
        "downstream tools. Edits propagate broadly on the next vendor sync.",
      severity: "amber",
    };
  }
  if (/^accessibility\/src\/[^/]+\.md$/.test(path)) {
    return {
      tier: "high-impact-accessibility",
      label: "Accessibility · all consumers",
      message:
        "Accessibility content is consumed by every component brief, the docs " +
        "site, and the FM/DS Kit. Edits affect WCAG guidance everywhere.",
      severity: "amber",
    };
  }

  // Default: normal per-component authoring.
  return {
    tier: "writable",
    label: "Writable",
    message: "",
    severity: "none",
  };
}
