import { isWysiwygEnabled } from "./editorFlags";
import safePathsJson from "../generated/wysiwyg-safe-paths.json";

/** The CI-derived set of source files whose Milkdown body round-trip is proven
 *  rich-safe. No longer a hand-curated allowlist: it is generated by
 *  editor/scripts/gen-wysiwyg-safe-paths.ts (which walks every editable file and
 *  actually round-trips it) and committed to
 *  editor/src/generated/wysiwyg-safe-paths.json. A CI drift check (editor-ci.yml)
 *  regenerates and fails if the committed set is stale, and the corpus gate
 *  (tests/markdown-engine/wysiwyg-safe-paths.test.ts) re-classifies every walked
 *  file with no skips. */
const WYSIWYG_SAFE_PATHS: ReadonlySet<string> = new Set(
  (safePathsJson as { paths: string[] }).paths,
);

/** True for any source file the registry marks WYSIWYG-safe (guard-verified). */
export function isWysiwygSafePath(path: string): boolean {
  return WYSIWYG_SAFE_PATHS.has(path);
}

/** True only for the three per-record app-context markdown kinds (apps,
 *  entities, patterns). Excludes the dist JSON, terminology.yml, nested paths,
 *  and other app-context files. Lives here (not in EditorShell) so screens can
 *  reuse it without a circular import. */
export function isAppContextFile(path: string): boolean {
  return /^app-context\/src\/(apps|entities|patterns)\/[^/]+\.md$/.test(path);
}

/** True only for component category records (components/src/categories/<slug>.md).
 *  Excludes AUTHORING.md and nested paths. */
export function isCategoryFile(path: string): boolean {
  return (
    /^components\/src\/categories\/[^/]+\.md$/.test(path) &&
    !/AUTHORING\.md$/.test(path)
  );
}

/** True only for the single words-to-avoid source file. Used by EditorShell
 *  to route to the FrontmatterBodyEditScreen without a raw string literal. */
export function isWordsToAvoidFile(path: string): boolean {
  return path === "content/src/writing/words-to-avoid.md";
}

/** The WYSIWYG body editor is used only for markdown whose body round-trips
 *  safely (app-context, categories, and registry-safe paths), and only when the
 *  alpha flag is on. Foundations/accessibility are dist-equivalent (guard-proven
 *  per file); content is rendered-equivalent (proven holistically by the
 *  derive-no-op gate). Precise predicates, not prefix matches. */
export function shouldUseWysiwyg(path: string): boolean {
  return (
    isWysiwygEnabled() &&
    (isAppContextFile(path) || isCategoryFile(path) || isWysiwygSafePath(path))
  );
}

/**
 * True for source markdown routed to MarkdownEditScreen (the raw CodeMirror or
 * WYSIWYG body editor). Matches accessibility and component domain files,
 * excluding structural meta-files.
 *
 * Lives here rather than in EditorShell so that leaf modules can ask what the
 * dispatch will accept without importing the UI graph. EditorShell re-exports
 * it, and remains the only place that ACTS on it.
 *
 * NOTE: intentionally does NOT match any content/src/**.md or foundations/src/*.md
 * anymore: ALL of those are form-routed via the frontmatterForms registry (see
 * `matchFrontmatterForm`, checked BEFORE this function). That includes
 * root-level content files (global-guidelines.md, format-spec.md); a form-routed
 * file with no frontmatter still lands in MarkdownEditScreen, but via
 * FrontmatterBodyEditScreen's no-frontmatter fallback, not through this.
 */
export function isPlainMarkdown(path: string): boolean {
  return (
    (/^accessibility\/src\/[^/]+\.md$/.test(path) ||
      /^components\/src\/(?!categories\/|AUTHORING\.md|EDITING-GUIDE\.md)[^/]+\/[^/]+\.md$/.test(
        path,
      )) &&
    !/AUTHORING\.md$/.test(path)
  );
}

/** True for a component's `_meta.yml`, which routes to MetaEditScreen. */
export function isMetaYaml(path: string): boolean {
  return /^components\/src\/[^/]+\/_meta\.yml$/.test(path);
}
