import React from "react";
import { Box, Flex, Heading, Popover, Text } from "@radix-ui/themes";
import { findReferences, findDefinitions } from "../lib/anchorIndex";
import { isGeneratedTarget } from "../lib/pathTiers";

export interface AnchorReferencesPopoverProps {
  slug: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onNavigate: (path: string) => void;
  /** DOM element the popover anchors to. CM6 owns the marker node, so we
   *  position an invisible <Popover.Anchor> at its bounding rect to give
   *  Radix's floating layout something concrete to attach to. */
  triggerEl?: HTMLElement | null;
}

export function AnchorReferencesPopover({
  slug,
  open,
  onOpenChange,
  onNavigate,
  triggerEl,
}: AnchorReferencesPopoverProps) {
  // Every row here navigates, so a generated target is a dead end: the click
  // lands on the RefusalBanner having lost the author's place (#684). The count
  // is taken after the filter, so it never advertises a row it will not render.
  //
  // But filtering is not the same as there being nothing. For nine of the
  // sixteen anchors in accessibility/src/components.md, EVERY indexed referrer
  // is a `components/dist/guidelines/*.json`, because the index scans .md and
  // dist JSON and never `_meta.yml`. Dropping those silently made this popover
  // say "No references in the substrate." about an anchor ten component
  // guidelines consume. What is withheld is stated.
  const allRefs = findReferences(slug);
  const refs = allRefs.filter((p) => !isGeneratedTarget(p));
  const generatedCount = allRefs.length - refs.length;
  const defs = findDefinitions(slug);
  const rect = triggerEl?.getBoundingClientRect();
  return (
    <Popover.Root open={open} onOpenChange={onOpenChange}>
      <Popover.Anchor>
        <span
          aria-hidden="true"
          style={{
            position: "fixed",
            left: rect?.left ?? 0,
            top: rect?.top ?? 0,
            width: rect?.width ?? 0,
            height: rect?.height ?? 0,
            pointerEvents: "none",
          }}
        />
      </Popover.Anchor>
      <Popover.Content size="2">
        <Flex direction="column" gap="2">
          <Heading as="h2" size="2">{`#${slug}`}</Heading>
          {defs.length > 0 && (
            <Text size="1" color="gray">
              defined in {defs.join(", ")}
            </Text>
          )}
          <Heading as="h3" size="1">
            {refs.length === 0 && generatedCount === 0
              ? "No references in the substrate."
              : refs.length === 0
                ? "No editable file references this."
                : `Referenced by ${refs.length} file${refs.length === 1 ? "" : "s"}`}
          </Heading>
          {generatedCount > 0 && (
            <Text size="1" color="gray">
              {generatedCount} generated{" "}
              {generatedCount === 1 ? "file" : "files"}{" "}
              {refs.length > 0
                ? generatedCount === 1
                  ? "also references"
                  : "also reference"
                : generatedCount === 1
                  ? "references"
                  : "reference"}{" "}
              this, and {generatedCount === 1 ? "is" : "are"} regenerated by CI
              rather than edited.
            </Text>
          )}
          {refs.length > 0 && (
            <Box>
              {refs.map((path) => (
                <Box
                  key={path}
                  py="1"
                  px="2"
                  style={{ cursor: "pointer" }}
                  onClick={() => onNavigate(path)}
                >
                  <Text size="2">{path}</Text>
                </Box>
              ))}
            </Box>
          )}
        </Flex>
      </Popover.Content>
    </Popover.Root>
  );
}
