"use strict";

// tests/render/alert-status-colors.test.js
//
// alert-banner's four registry types (Type = Primary | Success | Warning |
// Danger) must be four VISIBLY DIFFERENT things. They were not: every
// .ds-alert--* modifier set only border-left-color, and two of the four
// pointed at another type's token --
//
//   .ds-alert--success { border-left-color: var(--zen-color-icon-primary) }
//   .ds-alert--warning { border-left-color: var(--zen-color-icon-error) }
//
// so Success rendered as Info's blue and Warning as Danger's red. Asking for
// one variant returned another, which is #550's silent-substitution shape one
// layer down, in tokens rather than in the variant matrix.
//
// Both substitutions carried a code comment claiming the right token did not
// exist ("nearest available — no zen-success token", and a block note "no
// --zen-color-bg-* per-status tokens exist yet"). tokens.css defines
// --zen-color-icon-success, --zen-color-icon-warning and the whole
// --zen-color-bg-{info,success,warning,error} set, and has for as long as the
// alert rules have been there. The comment is what stopped anyone fixing it,
// so this file asserts the FACT the comment got wrong rather than trusting
// prose: every type names its own token, and every token it names resolves.
//
// Reads the SOURCE sheets, not components/render/dist/render.css: dist is
// regenerated by a later step than the source edit, so a dist read would judge
// the previous revision (same reasoning as css-owners.test.js).

var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("node:fs");
var path = require("node:path");

var REPO_ROOT = path.resolve(__dirname, "..", "..");
var BASE_CSS = fs.readFileSync(
  path.join(REPO_ROOT, "components/render/renderer/ds-base.css"),
  "utf8",
);
// render.css is concat(tokens.css, ds-base.css) — derive-canonical.js:300-306 —
// so tokens.css is where a var() the sheet names has to resolve.
var TOKENS_CSS = fs.readFileSync(
  path.join(REPO_ROOT, "tokens/tokens.css"),
  "utf8",
);

// The registry axis, in registry order. Danger is the DS's name for the type
// the Figma capture labels Error.
var TYPES = ["primary", "success", "warning", "danger"];

/** Declaration block of the first rule whose selector list contains `needle`. */
function ruleBody(needle) {
  var re = /([^{}]+)\{([^{}]*)\}/g;
  var m;
  while ((m = re.exec(BASE_CSS)) !== null) {
    if (m[1].indexOf(needle) !== -1) return m[2];
  }
  return null;
}

/** The var(--token) named by `prop` in `body`, or null. */
function tokenOf(body, prop) {
  if (body === null) return null;
  // Tolerates prettier's line wrapping inside var( ... ).
  var re = new RegExp(prop + "\\s*:\\s*var\\(\\s*(--[a-z0-9-]+)\\s*\\)", "i");
  var m = re.exec(body);
  return m ? m[1] : null;
}

function tokenIsDefined(name) {
  return new RegExp("\\" + name + "\\s*:").test(TOKENS_CSS);
}

test("each alert type paints its own background from its own status token", function () {
  var seen = {};
  var problems = [];
  TYPES.forEach(function (type) {
    var body = ruleBody(".ds-alert--" + type + " ");
    var token = tokenOf(body, "background");
    if (token === null) {
      problems.push(type + ": declares no background token");
      return;
    }
    if (!tokenIsDefined(token)) {
      problems.push(type + ": names " + token + ", undefined in tokens.css");
    }
    if (seen[token]) {
      problems.push(
        type + ": reuses " + token + ", already used by " + seen[token],
      );
    }
    seen[token] = type;
  });
  assert.deepEqual(problems, [], problems.join("\n"));
});

test("no two alert types resolve to the same icon colour", function () {
  var byToken = {};
  TYPES.forEach(function (type) {
    var body = ruleBody(".ds-alert--" + type + " .ds-alert__icon");
    var token = tokenOf(body, "color");
    assert.notEqual(
      token,
      null,
      type + ": no icon colour token (rule missing or not a var())",
    );
    assert.ok(
      tokenIsDefined(token),
      type + ": icon token " + token + " is undefined in tokens.css",
    );
    (byToken[token] = byToken[token] || []).push(type);
  });
  var shared = Object.keys(byToken).filter(function (t) {
    return byToken[t].length > 1;
  });
  assert.deepEqual(
    shared,
    [],
    shared
      .map(function (t) {
        return byToken[t].join(" and ") + " both render as " + t;
      })
      .join("\n"),
  );
});
