"use strict";
var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("node:fs");
var path = require("node:path");
var M = require("../../components/render/renderer/matrix.js");
var CLASSIFY = require("../../scripts/render/fidelity-classify.js");
var D = require("../../scripts/render/derive-from-renderer.js");

var REPO_ROOT = path.resolve(__dirname, "../..");
var BASE_CSS = fs.readFileSync(
  path.join(REPO_ROOT, "components/render/renderer/ds-base.css"),
  "utf8",
);

// Derived live from the renderer, not read out of components/render/dist/
// fragments. The dist is regenerated by a later step than the source edit that
// renames or retires a slug, so reading it meant this gate judged the PREVIOUS
// revision's markup: a newly added render slug had no fragment file at all
// (ENOENT, taking the whole file down) and a renamed one was silently checked
// against its old name's HTML. deriveFragment is the single producer of every
// file in that dist, so this asks the same question of the live source.
function fragmentHtml(slug) {
  return D.deriveFragment(slug);
}

function ruleCount(prefix) {
  var selRe = new RegExp("\\." + prefix + "(?![a-z0-9])(?!-(?!-))");
  var re = /([^{}]+)\{([^{}]*)\}/g;
  var n = 0;
  var m;
  while ((m = re.exec(BASE_CSS)) !== null) if (selRe.test(m[1])) n++;
  return n;
}

function fragmentClasses(slug) {
  var html = fragmentHtml(slug);
  var re = /class="([^"]*)"/g;
  var set = new Set();
  var m;
  while ((m = re.exec(html)) !== null) {
    m[1]
      .split(/\s+/)
      .filter(Boolean)
      .forEach(function (t) {
        if (/^ds-/.test(t)) set.add(t.split("--")[0].split("__")[0]);
      });
  }
  return set;
}

// Subject presence: a declared owner that matches no rule is a gate that
// verifies nothing while reporting success. See
// feedback_gate_must_assert_its_subject_was_present.
test("every render slug's owned prefixes resolve to at least one ds-base.css rule", function () {
  var dead = [];
  M.RENDER_SLUGS.forEach(function (slug) {
    M.ownedPrefixes(slug).forEach(function (p) {
      if (ruleCount(p) === 0) dead.push(slug + " -> ." + p);
    });
  });
  assert.deepEqual(dead, [], "owned prefixes with zero ds-base.css rules");
});

// Drift detector: the declaration is truth, but a declared owner that the
// fragment never emits means the render was renamed out from under the map.
test("every declared owner is a class the slug's fragment actually emits", function () {
  var absent = [];
  M.RENDER_SLUGS.forEach(function (slug) {
    var emitted = fragmentClasses(slug);
    M.ownedPrefixes(slug).forEach(function (p) {
      if (!emitted.has(p)) absent.push(slug + " -> ." + p);
    });
  });
  assert.deepEqual(absent, [], "declared owners absent from their fragment");
});

test("CSS_OWNERS carries no entry that merely restates ds-<slug>", function () {
  var redundant = Object.keys(M.CSS_OWNERS).filter(function (slug) {
    var o = M.CSS_OWNERS[slug];
    return o.length === 1 && o[0] === "ds-" + slug;
  });
  assert.deepEqual(redundant, [], "entries equal to the ds-<slug> default");
});

test("CSS_OWNERS has no key that is not a render slug", function () {
  var orphans = Object.keys(M.CSS_OWNERS).filter(function (slug) {
    return M.RENDER_SLUGS.indexOf(slug) === -1;
  });
  assert.deepEqual(orphans, [], "CSS_OWNERS keys absent from RENDER_SLUGS");
});

// The fallback, and the one thing CSS_OWNERS exists to override. The middle
// assertion used to name tag-stage and its two prefixes literally, which broke
// the day the 2026-08-12 fold-in retired that slug -- a hardcoded specimen for
// a property that is about the MAP, not about any one component. Both sides are
// read from CSS_OWNERS now, so the property survives the map's contents
// changing, and "an unmapped slug" is proven with a name no map can ever carry.
test("ownedPrefixes returns the declared prefixes for a mapped slug and ds-<slug> for an unmapped one", function () {
  assert.deepEqual(M.ownedPrefixes("no-such-slug-xyz"), [
    "ds-no-such-slug-xyz",
  ]);
  var mapped = Object.keys(M.CSS_OWNERS);
  assert.ok(mapped.length > 0, "CSS_OWNERS is empty, so this proves nothing");
  mapped.forEach(function (slug) {
    assert.deepEqual(
      M.ownedPrefixes(slug),
      M.CSS_OWNERS[slug],
      slug + ": ownedPrefixes must return the declared prefixes verbatim",
    );
    assert.notDeepEqual(
      M.ownedPrefixes(slug),
      ["ds-" + slug],
      slug + ": a declared entry must differ from the fallback",
    );
  });
});

// Final-review finding 2. fidelity-classify.js's cascade subjectKey excludes
// the owning prefix from a modifier-bucket key on purpose: tag-stage's
// `.ds-tag--orange` and `.ds-tag-stage--orange` restate the same modifier
// value under two different prefixes to override one color for itself
// alone, and that is only a safe collapse because both classes land on the
// literal same element (see the "Final-review finding 2" comment in
// fidelity-classify.js, subjectKey). If they were ever NOT on the same
// element, the loser would still resolve to `overridden` and the winner
// would still read `verified` even carrying a wrong color -- a false
// `verified`. This test pins that precondition for every slug that owns
// more than one prefix (today, only tag-stage), so a future renderer change
// that puts the two classes on different elements reds the build instead of
// silently producing a false verified.
//
// The modifier VALUES compared are read via CLASSIFY.classifySelector, the
// same function the cascade itself uses to decide "modifier" bucket
// membership, so "declared under a prefix" here means exactly what it means
// there.
function modifierValuesByPrefix(prefix) {
  var set = new Set();
  CLASSIFY.ownedRules(BASE_CSS, [prefix]).forEach(function (rule) {
    var cls = CLASSIFY.classifySelector(rule.selector, prefix);
    if (cls.bucket === "modifier") set.add(cls.modifier);
  });
  return set;
}

// Subject presence: after the 2026-08-12 tag fold-in, NO render slug owns more
// than one prefix (tag-stage was the only one, and it retired into
// tag-read-only's Type axis). The loop below therefore has nothing to compare
// today, and a `deepEqual(offenders, [])` on an empty walk is a gate reporting
// success while verifying nothing. So the multi-prefix population is reported
// by name and the precondition is asserted explicitly: if a future change
// reintroduces a multi-prefix slug, this walk starts biting again, and the
// cascade trade-off in fidelity-classify.js's subjectKey (which is only safe
// while the two classes land on the same element) is pinned once more.
test("multi-prefix slugs are enumerated, so the subjectKey precondition is never checked vacuously", function () {
  var multi = M.RENDER_SLUGS.filter(function (slug) {
    return M.ownedPrefixes(slug).length > 1;
  });
  assert.deepEqual(
    multi,
    [],
    "a render slug owns more than one ds-base.css prefix again (" +
      JSON.stringify(multi) +
      "). The same-element precondition below applies to it, and " +
      "fidelity-classify.js's subjectKey collapses its modifier rules across " +
      "prefixes on that basis -- confirm the classes really do land on one " +
      "element, then move this list into the walk below.",
  );
});

test("a modifier value declared under two or more of a multi-prefix slug's own prefixes appears in the same class attribute of that slug's fragment", function () {
  var offenders = [];
  M.RENDER_SLUGS.forEach(function (slug) {
    var prefixes = M.ownedPrefixes(slug);
    if (prefixes.length < 2) return;

    var owners = {}; // modifier value -> [prefix, prefix, ...]
    prefixes.forEach(function (p) {
      modifierValuesByPrefix(p).forEach(function (v) {
        (owners[v] = owners[v] || []).push(p);
      });
    });

    var html = fragmentHtml(slug);
    var classAttrs = [];
    var attrRe = /class="([^"]*)"/g;
    var am;
    while ((am = attrRe.exec(html)) !== null) {
      classAttrs.push(am[1].split(/\s+/).filter(Boolean));
    }

    Object.keys(owners).forEach(function (value) {
      var claimants = owners[value];
      if (claimants.length < 2) return;
      var neededClasses = claimants.map(function (p) {
        return p + "--" + value;
      });
      var together = classAttrs.some(function (tokens) {
        return neededClasses.every(function (c) {
          return tokens.indexOf(c) !== -1;
        });
      });
      if (!together) {
        offenders.push(
          slug +
            ": modifier '" +
            value +
            "' is declared under " +
            claimants.join(" and ") +
            ', but no single class="..." in ' +
            slug +
            ".html carries " +
            neededClasses.join(" and ") +
            " together",
        );
      }
    });
  });
  assert.deepEqual(offenders, []);
});
