"use strict";

// tests/render/sidenav-items-mode-stacks.test.js
//
// .ds-sidenav has TWO producers inside one renderer, and the rail's own rule
// has to be correct for both.
//
//   Groups mode  (props.Groups)  -> <nav>  __top  __bottom  </nav>   2 children
//   Items mode   (props.Items)   -> <nav>  __item × N        </nav>  N children
//
// The rule was `justify-content: space-between`, copied from the capture,
// which describes the Groups shape: two children, so the pair splits and the
// utilities group sits at the foot. Items mode hands the same rule seven
// direct children, and space-between spread seven 32px rows across the full
// 896px rail at a 139px pitch. That is every app sidebar in every generated
// flow, on both the plugin's HTML deliverable and this repo's canonical
// renders, and it read as a broken screen rather than a styling nit.
//
// jsdom applies no stylesheet, so no rendering test in this suite can see any
// of this (same structural blindness recorded in the instrument-theme guard).
// The guard therefore has to be a SOURCE JOIN: assert the shape the emitter
// produces AND the rule the sheet applies to that shape, in one file, so
// neither half can drift into disagreeing with the other again.
//
// Reads the SOURCE sheet, not components/render/dist/render.css: dist is
// regenerated by a later step than the source edit, so a dist read would judge
// the previous revision (same reasoning as css-owners.test.js).

var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("node:fs");
var path = require("node:path");

var REPO_ROOT = path.resolve(__dirname, "..", "..");
var BASE_CSS = fs.readFileSync(
  path.join(REPO_ROOT, "components/render/renderer/ds-base.css"),
  "utf8",
);
var DS_HTML_MAP = fs.readFileSync(
  path.join(REPO_ROOT, "components/render/renderer/html-renderers/ds-html-map.js"),
  "utf8",
);

// Return the declaration body of the FIRST rule whose selector list is exactly
// `selector`. Brace-counted rather than regex-matched so a nested block or a
// later rule mentioning the same class cannot be picked up by accident.
function ruleBody(css, selector) {
  var lines = css.split("\n");
  for (var i = 0; i < lines.length; i++) {
    if (lines[i].trim() !== selector + " {") continue;
    var depth = 1;
    var body = [];
    for (var j = i + 1; j < lines.length && depth > 0; j++) {
      depth += (lines[j].match(/{/g) || []).length;
      depth -= (lines[j].match(/}/g) || []).length;
      if (depth > 0) body.push(lines[j]);
    }
    return body.join("\n");
  }
  return null;
}

// Strip /* … */ so a rule's own prose about the value it no longer uses does
// not read as the declaration. Without this, the comment explaining why
// space-between was removed would itself trip the assertion.
function declarations(body) {
  return String(body == null ? "" : body).replace(/\/\*[\s\S]*?\*\//g, "");
}

test("the Items-mode branch emits nav rows as DIRECT children of .ds-sidenav", function () {
  var marker = "// ── Legacy mode (comma Items list, no icons) ──";
  var at = DS_HTML_MAP.indexOf(marker);
  assert.notEqual(
    at,
    -1,
    "the Items-mode branch of the side-nav leaf was not found in ds-html-map.js. " +
      "If it was renamed or removed, re-derive what shapes reach .ds-sidenav " +
      "before editing this guard: its whole point is that the sheet must suit " +
      "every shape the emitter produces.",
  );
  var branch = DS_HTML_MAP.slice(at, at + 900);
  assert.match(
    branch,
    /return '<nav class="' \+ navCls \+ '">' \+ navRows \+ "<\/nav>"/,
    "Items mode is expected to return its rows straight inside <nav>, with no " +
      "wrapper element. That is the shape .ds-sidenav's own rule has to suit.",
  );
  assert.equal(
    /ds-sidenav__top/.test(branch),
    false,
    "Items mode must not be wrapping its rows in __top. If it now does, the " +
      "rail has one shape again and this guard should be replaced, not relaxed.",
  );
});

test(".ds-sidenav must not distribute free space between its children", function () {
  var body = ruleBody(BASE_CSS, ".ds-sidenav");
  assert.notEqual(body, null, ".ds-sidenav rule not found in ds-base.css");
  var decls = declarations(body);

  assert.match(
    decls,
    /justify-content:\s*flex-start\s*;/,
    ".ds-sidenav must stack its children from the top.",
  );
  assert.equal(
    /justify-content:\s*space-(between|around|evenly)/.test(decls),
    false,
    "A distributing justify-content on .ds-sidenav spreads Items mode's N rows " +
      "across the full rail height. The Groups shape it was written for is " +
      "served by `.ds-sidenav__bottom { margin-top: auto }` instead, which is " +
      "correct for two children AND for seven.",
  );
});

test("Groups mode still anchors its utilities group, by the mechanism that does it", function () {
  // The first cut of this file asserted `__bottom { margin-top: auto }` here,
  // added alongside the space-between removal and described as "what replaces
  // it". Measuring the real sheet against the real emitted markup in a 896px
  // rail showed the declaration computes to 0px and neutralising it moves
  // __bottom not at all: __top's `flex: 1 1 auto` predates the change, absorbs
  // the free space, and is the whole mechanism. So the assertion protected an
  // inert declaration and its message named the wrong cause. It now asserts
  // the grow, and the two-child shape that grow assumes.
  var topRule = declarations(ruleBody(BASE_CSS, ".ds-sidenav__top"));
  assert.notEqual(topRule, "", ".ds-sidenav__top rule not found in ds-base.css");
  assert.match(
    topRule,
    /flex:\s*1 1 auto\s*;/,
    ".ds-sidenav__top must grow. With .ds-sidenav no longer distributing free " +
      "space, this is the only thing holding the utilities group at the rail's " +
      "foot; without it the two groups sit together at the top.",
  );
  assert.match(
    DS_HTML_MAP,
    /'<div class="ds-sidenav__bottom">' \+ bottomInner \+ "<\/div>"/,
    "Groups mode is expected to emit a __bottom wrapper as the rail's last " +
      "child. If it stops being last, __top growing no longer pushes it down.",
  );
});
