#!/usr/bin/env node
// Generates MAP.md from paths-manifest.json. Run from repo root via
// `node scripts/generate-map.js` (or `npm run generate:map`). Idempotent —
// same manifest input produces identical output. CI verifies no drift;
// humans don't edit MAP.md by hand.

'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(REPO_ROOT, 'paths-manifest.json');
const OUTPUT_PATH = path.join(REPO_ROOT, 'MAP.md');

// Group manifest entries by top-level directory (everything before first slash).
// Iteration order = manifest insertion order, which preserves the curator's
// intended sequence.
function groupByTopLevel(manifest) {
  const groups = new Map();

  function visit(key, entry, kind) {
    if (!entry) return;
    const target = entry.path || entry.dir;
    if (!target) return;
    const top = target.split('/')[0];
    if (!groups.has(top)) groups.set(top, []);
    groups.get(top).push({
      key,
      kind, // 'path' | 'collection'
      target,
      type: entry.type,
      origin: entry.origin,
      description: entry.description || '',
    });
  }

  for (const k in manifest.paths) visit(k, manifest.paths[k], 'path');
  for (const k in manifest.collections) visit(k, manifest.collections[k], 'collection');

  return groups;
}

function firstSentence(text) {
  if (!text) return '';
  // Take everything up to the first period followed by space-or-EOL.
  const m = text.match(/^(.+?)\.(\s|$)/);
  return (m ? m[1] : text).trim();
}

function generateMap(manifest) {
  const lines = [];
  lines.push('# Repository map');
  lines.push('');
  lines.push('> Auto-generated by `scripts/generate-map.js` from `paths-manifest.json`. Do not edit by hand.');
  lines.push('>');
  lines.push('> Knowledge version: **' + manifest.knowledge_version + '**.');
  lines.push('');
  lines.push('This is the orientation map for the repo. For the human-readable summary + status, see `README.md`. For the machine-readable contract, see `paths-manifest.json`.');
  lines.push('');
  lines.push('## Domains');
  lines.push('');

  const groups = groupByTopLevel(manifest);
  for (const [top, entries] of groups) {
    lines.push('### `' + top + '/`');
    lines.push('');
    for (const e of entries) {
      const tag = e.kind === 'collection' ? ' _(collection)_' : '';
      const originBadge = e.origin ? ' _[' + e.origin + ']_' : '';
      lines.push('- **`' + e.key + '`**' + tag + originBadge + ' — `' + e.target + '`');
      const fs1 = firstSentence(e.description);
      if (fs1) lines.push('  - ' + fs1 + '.');
    }
    lines.push('');
  }

  lines.push('## Coverage / debt');
  lines.push('');
  lines.push('See `components/dist/guidelines/coverage.md` — the documentation-debt matrix (auto-generated).');
  lines.push('');

  lines.push('## Consumers');
  lines.push('');
  lines.push('- **Actian DS Claude plugin** — pins a snapshot of this repo via `vendor-snapshot.yml`; consumes the manifest contract.');
  lines.push('- **Docs site** (in development) — reads via the same manifest.');
  lines.push('- **External / future AI agents** — `.md` URL pattern planned for next phase.');
  lines.push('');

  return lines.join('\n') + '\n';
}

function main() {
  const raw = fs.readFileSync(MANIFEST_PATH, 'utf8');
  const manifest = JSON.parse(raw);
  const out = generateMap(manifest);
  fs.writeFileSync(OUTPUT_PATH, out);
  console.log('[generate-map] wrote ' + OUTPUT_PATH + ' (' + out.length + ' bytes)');
}

module.exports = { generateMap };

if (require.main === module) main();
