#!/usr/bin/env node
"use strict";

// Federation Phase 1.5 — pure transform from
// components/registries/meta-kit/styles.json (already produced by
// sync-from-figma.js) into two markdown files:
//   components/text-styles.md
//   components/effect-styles.md
// No Figma API calls. Pure JSON-to-MD.

var fs = require("fs");
var path = require("path");

var REPO_ROOT = path.resolve(__dirname, "..");
var STYLES_PATH = path.join(
  REPO_ROOT,
  "components",
  "registries",
  "meta-kit",
  "styles.json",
);
var TEXT_OUT_PATH = path.join(REPO_ROOT, "components", "text-styles.md");
var EFFECT_OUT_PATH = path.join(REPO_ROOT, "components", "effect-styles.md");

function loadStyles() {
  if (!fs.existsSync(STYLES_PATH)) {
    throw new Error(
      "styles.json not found at " +
        STYLES_PATH +
        " — run sync-from-figma.js first",
    );
  }
  return JSON.parse(fs.readFileSync(STYLES_PATH, "utf8"));
}

function renderTextStyles(styles) {
  var lines = [
    "# DS Kit — Text Styles",
    "",
    "Auto-generated by `scripts/styles-to-md.js` from `components/registries/meta-kit/styles.json`.",
    "",
    "Total: " + styles.length + " text styles.",
    "",
    "| Style | Key | Font | Weight | Size | Line Height | Letter Spacing |",
    "|-------|-----|------|--------|------|-------------|----------------|",
  ];
  for (var s of styles) {
    var lh =
      s.lineHeight && s.lineHeight.unit === "PIXELS"
        ? s.lineHeight.value + "px"
        : "auto";
    var ls =
      s.letterSpacing && s.letterSpacing.unit === "PIXELS"
        ? s.letterSpacing.value.toFixed(2).replace(/\.?0+$/, "") + "px"
        : "0";
    lines.push(
      "| " +
        s.name +
        " | `" +
        s.key +
        "` | " +
        (s.fontFamily || "?") +
        " | " +
        (s.fontStyle || "?") +
        " | " +
        (s.fontSize || "?") +
        "px | " +
        lh +
        " | " +
        ls +
        " |",
    );
  }
  lines.push("");
  return lines.join("\n");
}

function renderEffectStyles(styles) {
  var lines = [
    "# DS Kit — Effect Styles",
    "",
    "Auto-generated by `scripts/styles-to-md.js` from `components/registries/meta-kit/styles.json`.",
    "",
    "Total: " + styles.length + " effect styles.",
    "",
    "| Style | Key | Effects |",
    "|-------|-----|---------|",
  ];
  for (var s of styles) {
    var effects = (s.effects || []).map(function (e) {
      if (e.type === "DROP_SHADOW" || e.type === "INNER_SHADOW") {
        var c = e.color || {};
        var rgba =
          "rgba(" +
          Math.round((c.r || 0) * 255) +
          ", " +
          Math.round((c.g || 0) * 255) +
          ", " +
          Math.round((c.b || 0) * 255) +
          ", " +
          (c.a || 1).toFixed(2) +
          ")";
        return (
          (e.offset ? e.offset.x + "px " + e.offset.y + "px " : "0px 0px ") +
          (e.radius || 0) +
          "px " +
          rgba
        );
      }
      return e.type;
    });
    lines.push(
      "| " + s.name + " | `" + s.key + "` | " + effects.join(" + ") + " |",
    );
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  var styles = loadStyles();
  var textStyles = styles.textStyles || [];
  var effectStyles = styles.effectStyles || [];
  fs.writeFileSync(TEXT_OUT_PATH, renderTextStyles(textStyles));
  fs.writeFileSync(EFFECT_OUT_PATH, renderEffectStyles(effectStyles));
  console.log(
    "[styles-to-md] wrote " +
      textStyles.length +
      " text styles + " +
      effectStyles.length +
      " effect styles",
  );
}

if (require.main === module) main();
module.exports = {
  renderTextStyles: renderTextStyles,
  renderEffectStyles: renderEffectStyles,
};
