"use strict";

// Auto-regenerates the appContext.* block in paths-manifest.json.
//
// Mirrors the structure of scripts/categories/derive-categories.js
// updatePathsManifest (lines 190-266) with these deltas:
//   - key prefix  : "appContext."
//   - dist         : one consolidated file (no per-slug leaves)
//   - collections  : appContextSrc (human) + appContextRecipesSrc (human)
//                    + appContextRecipes (ci, per-slug dist leaves)
//   - generator    : "scripts/app-context/derive-app-context.js"

const fs = require("node:fs");
const { writeManifest } = require("../lib/manifest-io");

const MANIFEST_APP_CONTEXT_NOTE =
  "appContext.* entries are auto-regenerated by scripts/app-context/derive-app-context.js. Do not hand-edit. Single consolidated dist JSON + src collection.";

function updatePathsManifest(manifestPath, opts) {
  opts = opts || {};
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  if (!manifest.paths) manifest.paths = {};
  if (!manifest.collections) manifest.collections = {};

  // 1. Drop existing appContext.* auto entries (and the old bare human leaf).
  // Also drop any stale collection entries under the appContext prefix.
  const dropped = [];
  Object.keys(manifest.paths).forEach((k) => {
    if (
      k === "appContext" ||
      k === "appContextBundle" ||
      k.indexOf("appContext.") === 0
    ) {
      dropped.push(k);
      delete manifest.paths[k];
    }
  });
  ["appContext.src", "appContextSrc", "appContextRecipesSrc", "appContextRecipes"].forEach((k) => {
    if (Object.prototype.hasOwnProperty.call(manifest.collections, k)) {
      delete manifest.collections[k];
    }
  });

  const added = [];

  // 2. Dist leaves — appContext (primary) + appContextBundle (embedded wrapper).
  // Named "appContextBundle" (not "appContext.bundle") to respect the leaf-XOR-namespace
  // convention: "appContext" is a leaf so no "appContext." prefix may be used in keys.
  manifest.paths["appContext"] = {
    path: "app-context/dist/app-context.json",
    type: "json",
    origin: "ci",
    generator: "scripts/app-context/derive-app-context.js",
    description:
      "Per-app patterns + persona + terminology (consolidated dist — do not edit)",
  };
  added.push("appContext");

  manifest.paths["appContextBundle"] = {
    path: "app-context/dist/app-context.bundle.json",
    type: "json",
    origin: "ci",
    generator: "scripts/app-context/derive-app-context.js",
    description:
      "Self-contained bundle wrapping the app-context dist under an `appContext` key; consumed by tools that embed the whole domain in a single JSON.",
  };
  added.push("appContextBundle");

  // 3. Collections — src (human) only; no byKey because dist is a single file.
  // Named "appContextSrc" (not "appContext.src") to avoid the leaf-XOR-namespace
  // collision: "appContext" is a leaf in paths, so nothing may use "appContext."
  // as a namespace prefix in collections — same pattern as "components.categoriesSrc".
  // recursive: true so gatherCoveredFiles walks into apps/, entities/, patterns/
  // subdirs and also picks up terminology.yml at the collection root.
  manifest.collections["appContextSrc"] = {
    dir: "app-context/src",
    pattern: "{kind}/{slug}.md",
    type: "markdown",
    origin: "human",
    recursive: true,
    description:
      "Authoring surface for app context. Per-kind subdirs: apps, entities, patterns. Terminology lives in terminology.yml (not covered by this collection).",
  };
  added.push("appContextSrc");

  // Recipes: authored JSON + per-slug dist leaves. A separate collection from
  // appContextSrc because that one is `{kind}/{slug}.md` and a recipe is JSON.
  // Keys avoid the "appContext." prefix for the same leaf-XOR-namespace reason.
  manifest.collections["appContextRecipesSrc"] = {
    dir: "app-context/src/recipes",
    pattern: "{slug}.json",
    type: "json",
    origin: "human",
    description:
      "Authoring surface for page recipes: the composition for a page shape named by an app-context pattern. Governed by schemas/app-context-recipe.json. Derived per slug to app-context/dist/recipes. See README.md in that directory.",
  };
  added.push("appContextRecipesSrc");

  manifest.collections["appContextRecipes"] = {
    dir: "app-context/dist/recipes",
    pattern: "{slug}.json",
    type: "json",
    origin: "ci",
    // The entry point, not the module. derive-recipes.js exports functions and
    // has no CLI, so running it exits 0 having written nothing, which is the
    // silent-success shape this repo keeps getting caught by. This is the only
    // `generator` in the manifest, so it also sets the precedent: name the file
    // a reader can actually run (`npm run derive:app-context` reaches it).
    generator: "scripts/app-context/derive-app-context.js",
    description:
      "Per-slug page recipe JSONs (validated + stamped). Resolved one at a time rather than folded into app-context.json, which is consumed whole: a single recipe exceeds 1400 lines, so bundling them would make every consumer pay for every archetype to read one.",
  };
  added.push("appContextRecipes");

  // 4. Zones — ensure appContextSrc + appContextBundle are classified in _zones.metadata.
  // Each non-namespaced key prefix must appear in _zones so the manifest-zones check passes.
  // "appContext" is already there; "appContextSrc" and "appContextBundle" must be added
  // separately (they cannot use the "appContext." prefix — that violates leaf-XOR-namespace).
  if (manifest._zones && Array.isArray(manifest._zones.metadata)) {
    for (const key of [
      "appContextSrc",
      "appContextBundle",
      "appContextRecipesSrc",
      "appContextRecipes",
    ]) {
      if (!manifest._zones.metadata.includes(key)) {
        manifest._zones.metadata.push(key);
      }
    }
    manifest._zones.metadata.sort();
  }

  // 5. Marker note
  manifest._notes = manifest._notes || {};
  manifest._notes.app_context_auto = MANIFEST_APP_CONTEXT_NOTE;

  if (!opts.dryRun) {
    writeManifest(manifestPath, manifest);
  }
  return { added, dropped, manifest };
}

module.exports = { updatePathsManifest };
