"use strict";

// Auto-regenerates the appContext.* block in paths-manifest.json.
//
// Mirrors the structure of scripts/categories/derive-categories.js
// updatePathsManifest (lines 190-266) with these deltas:
//   - key prefix  : "appContext."
//   - dist         : one consolidated file (no per-slug leaves)
//   - collections  : appContext.src (human) — no byKey (no per-slug dist)
//   - generator    : "scripts/app-context/derive-app-context.js"

const fs = require("node:fs");
const { writeManifest } = require("../lib/manifest-io");

const MANIFEST_APP_CONTEXT_NOTE =
  "appContext.* entries are auto-regenerated by scripts/app-context/derive-app-context.js. Do not hand-edit. Single consolidated dist JSON + src collection.";

function updatePathsManifest(manifestPath, opts) {
  opts = opts || {};
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  if (!manifest.paths) manifest.paths = {};
  if (!manifest.collections) manifest.collections = {};

  // 1. Drop existing appContext.* auto entries (and the old bare human leaf).
  // Also drop any stale collection entries under the appContext prefix.
  const dropped = [];
  Object.keys(manifest.paths).forEach((k) => {
    if (k === "appContext" || k.indexOf("appContext.") === 0) {
      dropped.push(k);
      delete manifest.paths[k];
    }
  });
  ["appContext.src", "appContextSrc"].forEach((k) => {
    if (Object.prototype.hasOwnProperty.call(manifest.collections, k)) {
      delete manifest.collections[k];
    }
  });

  const added = [];

  // 2. Single consolidated dist leaf — replaces the old bare "appContext" human entry
  manifest.paths["appContext"] = {
    path: "app-context/dist/app-context.json",
    type: "json",
    origin: "ci",
    generator: "scripts/app-context/derive-app-context.js",
    description:
      "Per-app patterns + persona + terminology (consolidated dist — do not edit)",
  };
  added.push("appContext");

  // 3. Collections — src (human) only; no byKey because dist is a single file.
  // Named "appContextSrc" (not "appContext.src") to avoid the leaf-XOR-namespace
  // collision: "appContext" is a leaf in paths, so nothing may use "appContext."
  // as a namespace prefix in collections — same pattern as "components.categoriesSrc".
  manifest.collections["appContextSrc"] = {
    dir: "app-context/src",
    pattern: "{kind}/{slug}.md",
    type: "markdown",
    origin: "human",
    description:
      "Authoring surface for app context. Per-kind subdirs: apps, entities, patterns. Terminology lives in terminology.yml (not covered by this collection).",
  };
  added.push("appContextSrc");

  // 4. Zones — ensure appContextSrc is classified in _zones.metadata.
  // The prefix "appContextSrc" (split(".")[0]) must appear in _zones so the
  // manifest-zones test passes. "appContext" is already there; "appContextSrc"
  // must be added separately because it cannot be named "appContext.src" (that
  // would violate the leaf-XOR-namespace convention).
  if (manifest._zones && Array.isArray(manifest._zones.metadata)) {
    if (!manifest._zones.metadata.includes("appContextSrc")) {
      manifest._zones.metadata.push("appContextSrc");
      manifest._zones.metadata.sort();
    }
  }

  // 5. Marker note
  manifest._notes = manifest._notes || {};
  manifest._notes.app_context_auto = MANIFEST_APP_CONTEXT_NOTE;

  if (!opts.dryRun) {
    writeManifest(manifestPath, manifest);
  }
  return { added, dropped, manifest };
}

module.exports = { updatePathsManifest };
