// Generates editor/src/generated/search-bodies.json: the searchable text of
// every addressable source file, so the header field can find a phrase written
// in the guidance rather than only a title (finding F2 — "sentence case" is a
// rule stated in 25 source files and search returned nothing for it).
//
// NOT committed. It is ~316 KB of prose that changes on every content edit, and
// committing it would put a large mechanical diff and a "run this command" step
// in the way of the content authors this editor exists for. It is generated by
// predev / prebuild / pretest instead, and .gitignore keeps it out.
//
// The walk is driven by ADDRESSED_DIRS and the filter by hashFor, both from
// src/lib/routes.ts, so the corpus IS the addressable set by construction: a
// file that search can find is a file the editor can open, and a section that
// becomes addressable becomes searchable in the same change.
//
// Run: npm run gen:search-bodies  (from editor/)
import { readdirSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ADDRESSED_DIRS } from "../src/lib/routes";
import { searchableText } from "../src/lib/searchBodyText";
import { searchKindForPath, type SearchBodyFile } from "../src/lib/searchBodies";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(SCRIPT_DIR, "..", "..");
const OUT = path.resolve(REPO, "editor", "src", "generated", "search-bodies.json");

/** Every markdown file under `dir`, repo-relative with forward slashes. A
 *  missing directory yields nothing rather than throwing: the corpus gate is
 *  what asserts a section did not vanish, and it says so by name. */
function markdownUnder(dir: string): string[] {
  let entries;
  try {
    entries = readdirSync(path.join(REPO, dir), { withFileTypes: true });
  } catch {
    return [];
  }
  const out: string[] = [];
  for (const e of entries) {
    const rel = `${dir}/${e.name}`;
    if (e.isDirectory()) out.push(...markdownUnder(rel));
    else if (e.name.endsWith(".md")) out.push(rel);
  }
  return out;
}

function main(): void {
  const walked = [...new Set(ADDRESSED_DIRS.flatMap(markdownUnder))].sort();

  const docs: SearchBodyFile["docs"] = [];
  let unoffered = 0;
  let empty = 0;
  for (const rel of walked) {
    // The consumer's own rule, not a second copy of it. It rejects a file the
    // editor cannot open (AUTHORING.md, a README — offering one would be
    // offering the refusal banner) and a section search does not carry.
    if (!searchKindForPath(rel)) {
      unoffered += 1;
      continue;
    }
    const text = searchableText(readFileSync(path.join(REPO, rel), "utf8"));
    if (text === "") {
      empty += 1;
      continue;
    }
    docs.push({ path: rel, text });
  }

  const output: SearchBodyFile = {
    _meta: {
      auto_generated: true,
      source: "editor/scripts/gen-search-bodies.ts",
      do_not_edit: true,
    },
    docs,
  };
  mkdirSync(path.dirname(OUT), { recursive: true });
  writeFileSync(OUT, JSON.stringify(output) + "\n");
  const bytes = docs.reduce((n, d) => n + d.text.length, 0);
  console.log(
    `search-bodies: ${docs.length} docs, ${Math.round(bytes / 1024)} KB of text ` +
      `(${walked.length} walked, ${unoffered} not offered, ${empty} empty) → ` +
      path.relative(REPO, OUT),
  );
}

main();
